

const Profile = () => {
    return (
        <div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere assumenda voluptatem maxime quos harum. Provident consequuntur numquam quasi excepturi et ipsa nemo minus eum quia sapiente soluta officiis accusamus qui doloribus quaerat, nisi aliquam animi porro. Sint, aspernatur! Distinctio accusamus consequuntur id. Totam in repellat odit quos dignissimos laboriosam exercitationem minima libero, veritatis iusto, ratione possimus molestias sequi. Laborum ipsum dolores, velit maxime repudiandae inventore laboriosam temporibus dicta! Cum ipsam qui libero cumque dolor reprehenderit sint omnis assumenda sit suscipit, iste repellendus in ad hic distinctio temporibus quaerat facere aliquid veritatis! Tempore nobis dignissimos unde dolore esse fugiat dolores, iure repellendus ex, recusandae tempora nulla facere provident corrupti maiores minima a? Maiores sunt aliquam autem ipsa! Inventore mollitia ad beatae ducimus reiciendis illo nobis quisquam asperiores ea. Perferendis nam doloremque, ipsam, minima assumenda, illum maiores quas ullam aliquam aliquid consequuntur velit voluptate. Vel ipsa in possimus, quis culpa distinctio molestias quod ut sint, velit dolorem fuga! Sunt voluptatem aliquam perferendis, repellat impedit doloribus dolore minus magni maxime, eaque rem explicabo dolor necessitatibus nemo quae deleniti. Modi nemo suscipit accusamus aspernatur dicta illum excepturi sit quae aliquid quaerat voluptate ex cumque magni, rem accusantium cum odio aut hic delectus nisi? Nam debitis minima, unde quod perferendis quos consequatur magnam sapiente dolorum voluptatem autem tempora, maiores ut qui nihil blanditiis odio? Recusandae obcaecati pariatur tenetur sit illum in labore, odio provident incidunt dicta vero veniam, perspiciatis accusantium suscipit molestiae modi eos libero asperiores voluptas! Fugit, et. Quia, voluptatibus itaque nemo vel at harum quibusdam dolor! Eius, rerum numquam nemo repudiandae praesentium odit minima ab cum ullam incidunt illum, eaque sit corporis accusamus, veritatis obcaecati. Hic perspiciatis debitis omnis culpa aperiam, modi dolorem voluptates, nam facilis sunt fugit harum perferendis asperiores. Placeat culpa nemo aliquid numquam harum, dolores fuga voluptatum asperiores vero laboriosam!</p>
        </div>
    );
};

export default Profile;